# Define triggers to run the pipeline when changes are made to the main branch
trigger:
- main

# Define the pool of agents to execute the pipeline jobs
pool:
  name: 'self hosted'
  demands:
  - agent.os -equals Linux

# Define the stages of the pipeline
stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/*.py'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Python files as artifacts'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'pipeline'


- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: TestJob
    displayName: 'Test'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - script: |
        python -m pip install pytest
        pytest test_hello_world.py
      displayName: 'Run Tests'


- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: TestJob
    displayName: 'Test'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
    - script: |
        python -m pip install pytest
        pytest test_hello_world.py
      displayName: 'Run Tests'


